# Generated by Django 5.0.2 on 2024-02-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
