# Generated by Django 5.0.2 on 2024-02-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
