# Generated by Django 5.0.2 on 2024-02-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_userinfo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=2),
        ),
    ]
