# Generated by Django 5.0.2 on 2024-02-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_userinfo_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='data',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
