# Generated by Django 5.0.2 on 2024-02-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_userinfo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='size',
        ),
    ]
