# Generated by Django 4.1 on 2024-02-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_usermessage_delete_department_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='age',
            field=models.CharField(max_length=3),
        ),
    ]
